name: Actualizar Noticias Diario
on:
  schedule:
    - cron: '0 12 * * *' # Se ejecuta a las 9 AM Argentina (12 UTC)
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install feedparser beautifulsoup4 pandas
      - name: Run script
        run: python update_news.py
      - name: Commit and Push
        run: |
          git config --global user.name "NewsBot"
          git config --global user.email "bot@github.com"
          git add index.html
          git commit -m "Actualización diaria de noticias" || exit 0
          git push
