name: Actualizar Noticias Diario
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install feedparser beautifulsoup4 requests
      - name: Run script
        run: python update_news.py
      - name: Commit and Push
        run: |
          git config --global user.name "NewsBot"
          git config --global user.email "bot@github.com"
          git add index.html
          git commit -m "Update news dashboard" || exit 0
          git push origin main --force
